name: Generate Snake

on:
  schedule: # Execute a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Mat-G25
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push
